---
npm:
  platforms:
    - name: linux
      os: ubuntu
      architecture: x86_64
      node_versions:
        - "6"
        - "8"
        - "10"
    - name: linux
      os: alpine
      architecture: x86_64
      node_versions:
        - "6"
        - "8"
        - "10"
    - name: linux
      os: ubuntu
      architecture: x86
      node_versions:
        - "6"
        - "8"
docker:
  builds:
    - path: .
      dockerfile: Dockerfile
      docker_repo: balena/open-balena-api
      publish: true
